apiVersion: apps
kind: Pod
metadata:
  name: valaxy-deployment
spec:
  containers:
     - name: valaxy-devops-project
       image: dileep95/spring:tagVersion
       imagePullPolicy: Always
       ports:
       - containerPort: 8050
